# Generated by Django 5.0.6 on 2024-06-06 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritemovies",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="casts",
            field=models.ManyToManyField(blank=True, to="movies.cast"),
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ManyToManyField(blank=True, to="movies.category"),
        ),
        migrations.AddField(
            model_name="favoritemovies",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
    ]
